

fn main() {
    let i: int
    let f: float
    let b: bool
    let c: char
    let arr: int[5]
    let d: double
    
    // Int should be 0
    if i != 0 {
        println "FAIL: int not 0"
    }

    // Bool should be false (0)
    if b {
        println "FAIL: bool not false"
    }
    
    // Char should be 0
    if c != 0 {
        println "FAIL: char not 0"
    }

    // Array should be zeroed
    if arr[0] != 0 {
        println "FAIL: arr not 0"
    }

    // Float shold be 0.0f
    if (f != 0.0f) {
        println "FAIL: float not 0.0f"
    }

    // Double shold be 0.0
    if (d != 0.0) {
        println "FAIL: double not 0.0"
    }

    println "PASS"
}
