
import "std/crypto/sha1.zc"
import "std/string.zc"

fn assert_true(cond: bool, msg: char*) {
    if (!cond) {
        !"Assertion failed: {msg}";
        exit(1);
    }
}

test "SHA1 Digest" {
    // "abc"
    // Expect: a9993e36 4706816a ba3e2571 7850c26c 9cd0d89d
    
    let msg = "abc";
    let d = Sha1::hash((u8*)msg, 3);
    
    let hex_str = String::new("");
    let buf: char[4];
    for(let i=0; i<20; i=i+1) {
        let val = d.bytes[i];
        let ptr = &buf[0];
        raw { sprintf(ptr, "%02x", val); }
        hex_str.append_c(&buf[0]);
    }
    
    assert_true(hex_str.eq_str("a9993e364706816aba3e25717850c26c9cd0d89d"), "SHA1(abc)");
    
    hex_str.free();
}
