
import "std/process.zc";
import "std/string.zc";

test "process output" {
    let cmd = Command::new("echo");
    cmd.arg("hello");
    
    let out = cmd.output();
    
    assert(out.exit_code == 0);
    // echo usually outputs newline
    assert(out.std_out.contains('h')); 
    assert(out.std_out.contains('e'));
    assert(out.std_out.contains('l'));
    assert(out.std_out.contains('o'));
    
    // out is dropped automatically
    // cmd is dropped automatically
}

test "process status" {
    let cmd = Command::new("true"); // true command returns 0
    let status = cmd.status();
    assert(status == 0);
}
