import "_emit_source_mapping_import.zc"

struct Log {
    // Empty.
}

impl Log {
    fn verbose(self, msg: char*) {
        printf("Log: %s\n", msg);
    }
}

@unused
struct Point {
    x: f64;
    y: f64;
}

impl Point {
    fn new() -> Self {
        return Point {
            x: 1.0,
            y: (f64)my_function(),
        }
    }
    fn mark_unused(self) { }
}

fn my_function() -> int {
    let log = Log {};
    
    let i = 0;
    i = i + 1;

    log.verbose("Hello, world!");

    return i;
}

fn main() {
    let val = my_function();

    let log = Log {};
    log.verbose("Hello, mars!");

    struct LocalPoint {
        x: int;
        y: int;
    }

    enum LocalState {
        Ready,
        Busy,
    }

    union LocalValue {
        i: int;
    }

    let local_point = LocalPoint { x: 3, y: 4 };
    let local_state = LocalState::Ready;
    let local_value = LocalValue { i: 8 };

    let point = Point {
        x: (f64)my_function(),
        y: 512.0,
    };
    point.mark_unused();
    assert(local_point.x == 3, "local struct failed");
    assert(local_state == LocalState::Ready, "local enum failed");
    assert(local_value.i == 8, "local union failed");

    for(let i = 0; i < 10; ++i)
    {
        val += 1;
        if val < 4
            continue;
        break;
    }

    if(my_function()
        && my_imported_function())
    {
        let _ = "Hello, world!";
    }

    if val < 5
        val += 5;
    else if val < 20
        val += 5;
    else
        val += 5;

    match val {
        1 => {
            log.verbose("1");
        },
        2 or 3 => {
            log.verbose("2 or 3");
        },
        4 .. 10 => {
            log.verbose("4 .. 10");
        },
        _ => {
            log.verbose("wildcard");
        }
    }
    
    val = my_imported_function();

    val = if val == 0 {
        1
    } else
        if val == 1 {
            2
        } else {
            3
        };

    printf("Done!\n");
}
